name: Scheduled marketplace update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/13 * * * *"

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3, 4, 5]
      max-parallel: 1
    steps:
      - name: Trigger update workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: update-marketplace.yml
          ref: main
